### ISSUE TITLE
Finaly some cfonb from CIC

### ISSUE THREAD

**Issue by fezfez** [silarhi/cfonb-parser#1]
First of all thanks for this amazing package.

During parsing i encounter several issue parsing cfonb from CIC.

- empty line can occur
- some 01 lines can be ignored with pattern "** PAS DE MOUVEMENT CE JOUR **" and "------------------------------"

But the most annoying is that 05 line (OperationDetail) are on multi line.

Are you okay if i make a PR to fix this ? (knowing that you actually throw an Exception if multiple 05 line are found for the same 01 line)

Thanks in advance :)

**Comment by guillaume-sainthillier** [comment]
Hello @fezfez 
For sure this lib could be improved, feel free to open PR to fix some bugs you've encountered.
You can also add the files from CIC to the `tests/fixtures` directory to cover more cases (with anonymised account numbers ofc).

Thanks,

**Comment by guillaume-sainthillier** [comment]
FYI i've just upload some guides to the `specs` directory, I hope this could help you :-)
