### ISSUE TITLE
Incorrect fixtures data

### ISSUE THREAD

**Issue by andrew-svirin** [silarhi/cfonb-parser#15]
I suspect that this line does not reading by reader. Am I wrong?
https://github.com/silarhi/cfonb-parser/blob/bdf5a4cdfe53c6d4e73ae61a6e6f01fa02bdfc2b/tests/fixtures/complex-test.txt#L25

**Comment by guillaume-sainthillier** [comment]
Thanks your for pointing this line, I will check this

**Comment by guillaume-sainthillier** [comment]
Indeed, this line should not be present, good catch 👍 

Thank you Andrew.
