### ISSUE TITLE
Unable to find a parser for the line

### ISSUE THREAD

**Issue by Antonyboc** [silarhi/cfonb-parser#185]
Hello

I have an error since 8 days.

From this code :

```
    /**
     * @return Statement[]
     */
    public function getStatements(Transaction $transaction): array
    {
        $content = wordwrap($transaction->getPlainOrderData(), 120, " \n", true);
        $reader = new Cfonb120Reader();

        return $reader->parse($content);
    }
```
    
Error : 
    
 Unable to find a parser for the line :
"0430004056800041EUR2 0001015354918281223  281223DE BRUYNE JULIETTE EI            0000000  "
(there is this space between EI and 0000000 '********' github remove it in this window.)

from : 

/vendor/silarhi/cfonb-parser/src/Parser/FileParser.php dans Silarhi\Cfonb\Parser\FileParser::findSupportedParserForLine à la ligne 61

Can you help me please ?

**Comment by guillaume-sainthillier** [comment]
Hello @Antonyboc, could you please put the exact line in error into a code block?

**Comment by Antonyboc** [comment]
Hello @guillaume-sainthillier 

`"0430004056800041EUR2 0001015354918281223  281223DE BRUYNE JULIETTE EI            0000000  "`

**Comment by guillaume-sainthillier** [comment]
@Antonyboc your line is 90 length long so it cannot work with CFONB 120 or CFONB 240.

You should review the whole file and check for content wrapping error.
