### ISSUE TITLE
reference mandatory in Operation

### ISSUE THREAD

**Issue by sbarbo** [silarhi/cfonb-parser#24]
Hi!
I used your library today, and i have a little, i have an official bank extract where the reference field is empty in the 04 line.
So the contruct of the Operation object failed because the field 'reference' cannot be null.
Could you think it is possible to make it nullable (?string reference instead of string reference) ?
I know that in the documentation of the format, the field is mandatory, but if it is empty...
Thank you.
Sylvain

**Comment by guillaume-sainthillier** [comment]
Hello,
This package is open source, if you have an empty reference from your bank in your 04 line, feel free to make a PR which cover your case 👍

**Comment by guillaume-sainthillier** [comment]
I'm closing this issue for now. Feel free to open it with a PR 👍
