### ISSUE TITLE
End of line

### ISSUE THREAD

**Issue by ghost** [silarhi/cfonb-parser#270]
If parsed file is in DOS format, the end line is \r\n and not only \n
So parser will throw an exception

**Comment by guillaume-sainthillier** [comment]
Hello, thanks for feedback. Could you provide a PR with the fix and add a test for this kind of files?

**Comment by ghost** [comment]
Sorry I don't have fix nor test for this

For now, I just apply `$content = str_replace("\r\n", "\n", $content)` before calling `$reader->parse($content)`

But I think it's should be done in `FileParser::parse` function ?

**Comment by guillaume-sainthillier** [comment]
Yes it could be added there!

**Comment by ghost** [comment]
Another case with "end of line" problem is when all content is on single line.

that is take into consideration into `FileParser::parse` with
        if (strlen($content) > $lineLength && !str_contains($content, "\n")) {
            $content = chunk_split($content, $lineLength, "\n");
        }

But sometimes, there is jsut one \n at the very end. Maybe the whole correction for 2 problem should be
`$content = rtrim(str_replace("\r\n", "\n", $content), "\n");`
at the begin of the function ?

**Comment by guillaume-sainthillier** [comment]
It would be a way of improvement, if you could provide the file with these 2 differents cases and add it tests for it then we will be sure about the consistency of parsing

**Comment by fezfez** [comment]
@guillaume-sainthillier see #275
