### ISSUE TITLE
[QA] Handle multiple phpunit files

### ISSUE THREAD

**Issue by guillaume-sainthillier** [silarhi/cfonb-parser#28]
We need to keep BC & tests working from php 7.2 to php 8.

This lead us to keep 2 phpunit files, one for phpunit 8 and the other for phpunit 9.
Maybe the solution is to use phpunit 8 only for now.

WDYT @fezfez?

**Comment by fezfez** [comment]
i think phpunit 8 is not compatible with php 8.X, lets give it a try

**Comment by fezfez** [comment]
a better solution would be to have two branches, 2.X for php 7 and 3.X for php 8 and maintain both

**Comment by guillaume-sainthillier** [comment]
DONE in PR #29
