### ISSUE TITLE
Problem with parsing CIC files

### ISSUE THREAD

**Issue by mathias1981** [silarhi/cfonb-parser#44]
Hello,

I receive the attached cfonb files from CIC and the parser is not working, i get the attached error

[20221205.99.283300.releveautomatique.2f8d7d8a_20221205_052803 (1).txt](https://github.com/silarhi/cfonb-parser/files/10259477/20221205.99.283300.releveautomatique.2f8d7d8a_20221205_052803.1.txt)

![bug](https://user-images.githubusercontent.com/9075594/208433661-dc4cf75c-46d1-4ae8-92bc-7fe4da699588.png)

Can you help me?

Regards

**Comment by fezfez** [comment]
Hello !

Can you create a PR with this failing case ?

**Comment by mathias1981** [comment]
Hello,

I just did it, thanks again!

**Comment by mathias1981** [comment]
@fezfez i am not sure i created correctly the PR, with the good branch... Tell me if i must change something.

**Comment by guillaume-sainthillier** [comment]
We would like to have a PR where you create a new test case with your failing file.

you have some examples here: https://github.com/silarhi/cfonb-parser/tree/3.x/tests/fixtures
And here: https://github.com/silarhi/cfonb-parser/blob/3.x/tests/Cfonb120ReaderTest.php

**Comment by mathias1981** [comment]
@guillaume-sainthillier when i try to create a PR, i cannot do it only on branch 3.x, see screenshot bellow. But i created what you ask, bellow are the cfonb file in trouble + a php script to test it.

[test_parse.php.txt](https://github.com/silarhi/cfonb-parser/files/10307501/test_parse.php.txt)

[test_cfonb.txt](https://github.com/silarhi/cfonb-parser/files/10307503/test_cfonb.txt)

And i get this error :
![image](https://user-images.githubusercontent.com/9075594/209652191-24314f12-2826-4db2-8c0c-94def2c32719.png)


Thanks a lot for your time and help !

The problem with pull request i told you about :

![image](https://user-images.githubusercontent.com/9075594/209652228-59ae12ff-c06c-4158-a336-05b6e39e416c.png)

**Comment by guillaume-sainthillier** [comment]
You have to fork the project, do the changes on your local repo and then create the based based on your fork (see the "compare accross fork" link)

**Comment by guillaume-sainthillier** [comment]
I'm closing this issue as your problem was related to line endings
